# Vuelta atrás (Backtracking)

Con la estrategia de vuelta atrás se van explorando una a una las posibles soluciones, en caso de encontrarnos con una respuesta incorrecta (ej. false), volvemos atrás y probamos una nueva opción entre todas las posibilidades.

Problema: ¿Cómo podemos posicionar 8 reinas en un tablero de ajedrez sin que se "mate" una a la otra"?

Hacer una matriz con numpy para simular el tablero de ajedrez:

In [6]:
tablero = np.zeros((8,8),dtype=int) 
print(tablero) #tablero sin reinas

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Definimos la función que se encarga de posicionar a las reinas verificando que no haya otra en "su camino":

In [7]:
import numpy as np

def posicionar_reinas(f,c):
    for k in range(8): #Checar por cada columna y fila si existe una reina
        if tablero[f][k] == 1 or tablero[k][c] == 1:
            return False
        
    for n in range(8): # check diagonal
        for m in range(len(tablero)):
            if(f+c == n + m) or (f-c == n-m):
                if tablero[n][m] == 1:
                    return False
    return 1



Definimos la función que posicione el número de reinas deseadas, debe de ser de acuerdo al tamaño del tablero.
Esta función reinas() utiliza la función posicionar_reinas(f,c) definida arriba.

In [12]:
def reinas(n):
    if n == 0:
        return 1
    for i in range(8):
        for j in range(8):
            if posicionar_reinas(i,j) and tablero[i][j] != 1:
                tablero[i][j] = 1
                if reinas(n-1):
                    return True
                else: 
                    tablero[i][j] = 0
    return False


Ahora probamos la función con 8 reinas a posicionar 

In [13]:
reinas(8)

True

Imprimimos el tablero con las 8 reinas posicionadas (denotadas como 1).

In [14]:
print(tablero)

[[1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]]
